spring:
  profiles:
    active: gm

---
spring:
  config:
    activate:
      on-profile: ht
hdfs:
  path: hdfs://node1:8020
  username: root

spark:
  path: spark://xxx.xx.xx.xx:7077

---

spring:
  config:
    activate:
      on-profile: gm

hdfs:
  path: hdfs://192.168.145.131:8020
  username: root

spark:
  path: spark://192.168.145.131:7077

---