spring:
  profiles:
    active: gm

---
spring:
  config:
    activate:
      on-profile: ht
hdfs:
  path: hdfs://192.168.88.131:8020
  username: root

spark:
  path: spark://192.168.88.131:7077

---

spring:
  config:
    activate:
      on-profile: gm

hdfs:
  path: hdfs://192.168.88.131:8020
  username: root

spark:
  path: spark://192.168.88.131:7077

---