spring:
  profiles:
    active: gm

---
spring:
  config:
    activate:
      on-profile: ht
hdfs:
  path: hdfs://node1:8020
  username: root

spark:
  path: spark://node1:7077

streamingDatSever:
  path: xx.xx.xx.xx

mysql:
  ip: sh-cynosdbmysql-grp-5tpsbo9c.sql.tencentcdb.com
  username: flight_analysis_user
  password: 123456azM
  port: 26211
  dbName: flight_analysis
---

spring:
  config:
    activate:
      on-profile: gm

hdfs:
  path: hdfs://192.168.145.131:9000
  username: root

spark:
  path: spark://192.168.145.131:7077

streamingDataSever:
  path: xx,xx.xx.xx

mysql:
  ip: sh-cynosdbmysql-grp-5tpsbo9c.sql.tencentcdb.com
  username: flight_analysis_user
  password: 123456azM
  port: 26211
  dbName: flight_analysis
---